name: CI - Gestion des utilisateurs et profiles (Main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Maven lint (Checkstyle)
        run: mvn checkstyle:check

  test:
    name: Run Tests with PostgreSQL
    runs-on: ubuntu-latest
    needs: lint

    services:
      postgres-spring:
        image: postgres:16
        env:
          POSTGRES_DB: dbGestionDesUtilisateurs
          POSTGRES_USER: springuser
          POSTGRES_PASSWORD: springpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U springuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres Spring..."
          until pg_isready -h localhost -p 5432 -U springuser; do sleep 5; done

      - name: Run Maven tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/dbGestionDesUtilisateurs
          SPRING_DATASOURCE_USERNAME: springuser
          SPRING_DATASOURCE_PASSWORD: springpass
        run: mvn test

  analyze:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=spechofy
          -Dsonar.projectName=spechofy
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
